version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./src/main/webapp:/usr/share/nginx/html"
    depends_on:
      - lavagna-app

  lavagna-app:
    build: ./
    # ports:
    #   - 8080:8080
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lavagna
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
    volumes:
       - mysql_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 20s
      retries: 20

volumes:
  mysql_db_data: