version: '3'

services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - 80:80
      - 8081:8081
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./src/main/webapp:/usr/share/nginx/html"
    depends_on:
      - lavagna-app
      - doc
    networks:
      - net1

  lavagna-app:
    build: ./
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - net1
      - net2

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lavagna
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
    volumes:
       - mysql_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 20s
      retries: 20
    networks:
      - net2

  doc:
    build: 
      dockerfile: Dockerfile.doc
    networks:
      - net1

volumes:
  mysql_db_data:

networks:
  net1:
    driver: bridge
  net2:
    driver: bridge
